/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('users').del()
  await knex('users').insert([
    {
      auth0_id: 1,
      name: 'Darlene',
      location: 'CBD',
      bio: 'Axis axis',
      email: 'yolo0@yolasite.com',
      phone_number: 9,
      approachable: true,
      img: './images/users/richard-Walker.jpg',
      walker: true,
      owner: false,
    },
    {
      auth0_id: 2,
      name: 'Max',
      location: 'South',
      bio: 'Columba palumbus',
      email: 'vmax1@census.gov',
      phone_number: 10,
      approachable: false,
      img: './images/users/chris-Walker.jpg',
      walker: true,
      owner: false,
    },
    {
      auth0_id: 3,
      name: 'Wade',
      location: 'West',
      bio: 'Axis axis',
      email: 'yolo0@yolasite.com',
      phone_number: 9,
      approachable: true,
      img: './images/users/wade-Walker.jpg',
      walker: true,
      owner: false,
    },
    {
      auth0_id: 4,
      name: 'Sarah',
      location: 'North',
      bio: 'Columba palumbus',
      email: 'vmax1@census.gov',
      phone_number: 10,
      approachable: false,
      img: './images/users/sayo-walker.jpg',
      walker: true,
      owner: false,
    },
    {
      auth0_id: 5,
      name: 'Jacob',
      location: 'Youhao',
      bio: 'Rhea americana',
      email: 'jwaghorn3@dyndns.org',
      phone_number: 11,
      approachable: false,
      img: './images/users/sample.jpg',
      walker: false,
      owner: true,
    },
    {
      auth0_id: 6,
      name: 'Verne',
      location: 'Kulonkali',
      bio: 'Pteronura brasiliensis',
      email: 'vdannell4@netscape.com',
      phone_number: 10,
      approachable: false,
      img: './images/users/sample.jpg',
      walker: false,
      owner: true,
    },
    {
      auth0_id: 7,
      name: 'Madeline',
      location: 'Bayan Qagan',
      bio: 'Turtur chalcospilos',
      email: 'mmanifield5@live.com',
      phone_number: 11,
      approachable: true,
      img: './images/users/sample.jpg',
      walker: false,
      owner: true,
    },
  ])
}
